name: Build Docker Images

# tune this section for triggers
on:
  workflow_dispatch:
    inputs:
      msg:
        description: "Workflow"
        default: "Run"
  push:
    branches: [ master, develop ]
    paths-ignore:
      # - '.github/workflows/**'
jobs:
  dustman:
    runs-on: sber-automl
    steps:
      - name: Cleanup Workspace
        run: |
          echo "Cleaning up..."
          rm -rf "${{ github.workspace }}"
 